// =============================================================================
// Demo Data - Static content to be replaced by CMS later
// =============================================================================

import {
  Workout,
  WorkoutProgram,
  MealPlan,
  Goal,
  BrandCampaign,
  SponsoredChallenge,
  ProductPlacement,
  Coupon,
  UserProgress,
  Achievement,
  Recovery,
} from "./types";

// =============================================================================
// Workouts
// =============================================================================
export const workouts: Workout[] = [
  {
    id: "w1",
    title: "Morning HIIT Blast",
    description:
      "High-intensity interval training to kickstart your metabolism and energize your day. Perfect for burning calories fast.",
    muscleGroups: ["full-body", "cardio"],
    difficulty: "intermediate",
    duration: 25,
    equipment: ["none"],
    calories: 320,
    thumbnailUrl: "/images/workouts/workout-morning-hiit-blast.jpg",
    exercises: [
      { id: "e1", name: "Jumping Jacks", sets: 3, reps: "45 sec", restSeconds: 15 },
      { id: "e2", name: "Burpees", sets: 3, reps: "10", restSeconds: 30 },
      { id: "e3", name: "Mountain Climbers", sets: 3, reps: "30 sec", restSeconds: 15 },
      { id: "e4", name: "High Knees", sets: 3, reps: "45 sec", restSeconds: 15 },
      { id: "e5", name: "Squat Jumps", sets: 3, reps: "12", restSeconds: 30 },
    ],
    tags: ["hiit", "cardio", "no-equipment", "fat-burning"],
    createdAt: "2024-01-15T08:00:00Z",
    updatedAt: "2024-01-15T08:00:00Z",
  },
  {
    id: "w2",
    title: "Upper Body Strength",
    description:
      "Build a powerful upper body with this comprehensive dumbbell workout targeting chest, back, shoulders, and arms.",
    muscleGroups: ["chest", "back", "shoulders", "arms"],
    difficulty: "intermediate",
    duration: 45,
    equipment: ["dumbbells", "bench"],
    calories: 280,
    thumbnailUrl: "/images/workouts/workout-upper-body-strength.jpg",
    exercises: [
      { id: "e6", name: "Dumbbell Bench Press", sets: 4, reps: "10-12", restSeconds: 60 },
      { id: "e7", name: "Bent Over Rows", sets: 4, reps: "10-12", restSeconds: 60 },
      { id: "e8", name: "Shoulder Press", sets: 3, reps: "10-12", restSeconds: 60 },
      { id: "e9", name: "Bicep Curls", sets: 3, reps: "12-15", restSeconds: 45 },
      { id: "e10", name: "Tricep Dips", sets: 3, reps: "12-15", restSeconds: 45 },
    ],
    tags: ["strength", "upper-body", "dumbbells"],
    createdAt: "2024-01-16T08:00:00Z",
    updatedAt: "2024-01-16T08:00:00Z",
  },
  {
    id: "w3",
    title: "Core Crusher",
    description:
      "Strengthen and define your core with this intense abdominal workout. No equipment needed, just determination.",
    muscleGroups: ["core"],
    difficulty: "beginner",
    duration: 20,
    equipment: ["none"],
    calories: 150,
    thumbnailUrl: "/images/workouts/workout-core-crusher.jpg",
    exercises: [
      { id: "e11", name: "Plank Hold", sets: 3, reps: "45 sec", restSeconds: 30 },
      { id: "e12", name: "Bicycle Crunches", sets: 3, reps: "20", restSeconds: 30 },
      { id: "e13", name: "Leg Raises", sets: 3, reps: "15", restSeconds: 30 },
      { id: "e14", name: "Russian Twists", sets: 3, reps: "20", restSeconds: 30 },
      { id: "e15", name: "Dead Bug", sets: 3, reps: "12 each side", restSeconds: 30 },
    ],
    tags: ["core", "abs", "no-equipment", "beginner-friendly"],
    createdAt: "2024-01-17T08:00:00Z",
    updatedAt: "2024-01-17T08:00:00Z",
  },
  {
    id: "w4",
    title: "Leg Day Power",
    description:
      "Build strong, powerful legs with compound movements. This workout targets quads, hamstrings, and glutes.",
    muscleGroups: ["legs", "glutes"],
    difficulty: "advanced",
    duration: 50,
    equipment: ["barbell", "dumbbells"],
    calories: 420,
    thumbnailUrl: "/images/workouts/workout-leg-day-power.jpg",
    exercises: [
      { id: "e16", name: "Barbell Squats", sets: 4, reps: "8-10", restSeconds: 90 },
      { id: "e17", name: "Romanian Deadlifts", sets: 4, reps: "10-12", restSeconds: 90 },
      { id: "e18", name: "Walking Lunges", sets: 3, reps: "12 each leg", restSeconds: 60 },
      { id: "e19", name: "Leg Press", sets: 3, reps: "12-15", restSeconds: 60 },
      { id: "e20", name: "Calf Raises", sets: 4, reps: "15-20", restSeconds: 45 },
    ],
    tags: ["legs", "strength", "compound", "advanced"],
    createdAt: "2024-01-18T08:00:00Z",
    updatedAt: "2024-01-18T08:00:00Z",
  },
  {
    id: "w5",
    title: "Yoga Flow",
    description:
      "A gentle yet effective yoga flow to improve flexibility, balance, and mental clarity. Perfect for recovery days.",
    muscleGroups: ["full-body"],
    difficulty: "beginner",
    duration: 30,
    equipment: ["none"],
    calories: 120,
    thumbnailUrl: "/images/workouts/workout-1544367567.jpg",
    exercises: [
      { id: "e21", name: "Sun Salutation A", sets: 3, reps: "5 rounds", restSeconds: 0 },
      { id: "e22", name: "Warrior Sequence", sets: 1, reps: "Hold 30 sec each", restSeconds: 0 },
      { id: "e23", name: "Balance Poses", sets: 1, reps: "Hold 30 sec each", restSeconds: 0 },
      { id: "e24", name: "Hip Openers", sets: 1, reps: "2 min each side", restSeconds: 0 },
      { id: "e25", name: "Savasana", sets: 1, reps: "5 min", restSeconds: 0 },
    ],
    tags: ["yoga", "flexibility", "recovery", "mindfulness"],
    createdAt: "2024-01-19T08:00:00Z",
    updatedAt: "2024-01-19T08:00:00Z",
  },
  {
    id: "w6",
    title: "Quick Cardio Burn",
    description:
      "Short on time? This 15-minute cardio session will get your heart pumping and calories burning fast.",
    muscleGroups: ["cardio", "full-body"],
    difficulty: "beginner",
    duration: 15,
    equipment: ["none"],
    calories: 180,
    thumbnailUrl: "/images/workouts/workout-1538805060514.jpg",
    exercises: [
      { id: "e26", name: "Marching in Place", sets: 1, reps: "2 min", restSeconds: 0 },
      { id: "e27", name: "Step Touch", sets: 1, reps: "1 min", restSeconds: 0 },
      { id: "e28", name: "Jumping Jacks", sets: 3, reps: "30 sec", restSeconds: 15 },
      { id: "e29", name: "High Knees", sets: 3, reps: "30 sec", restSeconds: 15 },
      { id: "e30", name: "Cool Down Stretch", sets: 1, reps: "2 min", restSeconds: 0 },
    ],
    tags: ["cardio", "quick", "no-equipment", "beginner-friendly"],
    createdAt: "2024-01-20T08:00:00Z",
    updatedAt: "2024-01-20T08:00:00Z",
  },
];

// =============================================================================
// Workout Programs
// =============================================================================
export const workoutPrograms: WorkoutProgram[] = [
  {
    id: "p1",
    title: "7-Day Fat Burner",
    description:
      "An intensive week-long program designed to maximize calorie burn and kickstart your weight loss journey.",
    goal: "weight-loss",
    duration: "7-day",
    difficulty: "intermediate",
    workoutsByDay: [
      { day: 1, workoutId: "w1", isRestDay: false },
      { day: 2, workoutId: "w2", isRestDay: false },
      { day: 3, workoutId: "w3", isRestDay: false },
      { day: 4, workoutId: null, isRestDay: true, notes: "Active recovery - light walk" },
      { day: 5, workoutId: "w4", isRestDay: false },
      { day: 6, workoutId: "w1", isRestDay: false },
      { day: 7, workoutId: "w5", isRestDay: false },
    ],
    thumbnailUrl: "/images/workouts/workout-1517836357463.jpg",
    featured: true,
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
  },
  {
    id: "p2",
    title: "30-Day Strength Builder",
    description:
      "Build lean muscle mass and increase your strength with this comprehensive month-long training program.",
    goal: "strength",
    duration: "30-day",
    difficulty: "intermediate",
    workoutsByDay: Array.from({ length: 30 }, (_, i) => ({
      day: i + 1,
      workoutId: i % 7 === 6 ? null : workouts[i % 5].id,
      isRestDay: i % 7 === 6,
      notes: i % 7 === 6 ? "Complete rest day" : undefined,
    })),
    thumbnailUrl: "/images/workouts/workout-30-day-strength-builder.jpg",
    featured: true,
    createdAt: "2024-01-02T08:00:00Z",
    updatedAt: "2024-01-02T08:00:00Z",
  },
  {
    id: "p3",
    title: "Beginner Bootcamp",
    description:
      "New to fitness? This gentle introduction will help you build a solid foundation and healthy habits.",
    goal: "general-fitness",
    duration: "14-day",
    difficulty: "beginner",
    workoutsByDay: Array.from({ length: 14 }, (_, i) => ({
      day: i + 1,
      workoutId: i % 3 === 2 ? null : ["w3", "w5", "w6"][i % 3],
      isRestDay: i % 3 === 2,
    })),
    thumbnailUrl: "/images/workouts/workout-beginner-bootcamp.jpg",
    featured: false,
    createdAt: "2024-01-03T08:00:00Z",
    updatedAt: "2024-01-03T08:00:00Z",
  },
];

// =============================================================================
// Meal Plans
// =============================================================================
export const mealPlans: MealPlan[] = [
  {
    id: "m1",
    title: "High Protein Meal Plan",
    description:
      "Fuel your muscle growth with this protein-packed meal plan. Perfect for strength training and muscle building.",
    dietType: "high-protein",
    macros: { protein: 180, carbs: 200, fat: 70, fiber: 35 },
    allergyTags: [],
    totalCalories: 2150,
    thumbnailUrl: "/images/programs/meal-plan-high-protein-meal-plan.jpg",
    meals: [
      {
        id: "meal1",
        name: "Protein Power Breakfast",
        type: "breakfast",
        calories: 520,
        macros: { protein: 45, carbs: 40, fat: 18 },
        ingredients: ["4 egg whites", "2 whole eggs", "spinach", "whole grain toast", "avocado"],
        prepTime: 10,
        cookTime: 10,
        imageUrl: "/images/programs/meal-plan-1525351484163.jpg",
      },
      {
        id: "meal2",
        name: "Grilled Chicken Salad",
        type: "lunch",
        calories: 580,
        macros: { protein: 50, carbs: 35, fat: 25 },
        ingredients: ["grilled chicken breast", "mixed greens", "quinoa", "cherry tomatoes", "olive oil"],
        prepTime: 15,
        cookTime: 15,
        imageUrl: "/images/meals/meal-grilled-chicken-salad.jpg",
      },
      {
        id: "meal3",
        name: "Salmon & Sweet Potato",
        type: "dinner",
        calories: 650,
        macros: { protein: 55, carbs: 55, fat: 22 },
        ingredients: ["salmon fillet", "sweet potato", "broccoli", "lemon", "herbs"],
        prepTime: 10,
        cookTime: 25,
        imageUrl: "/images/meals/meal-salmon-sweet-potato.jpg",
      },
      {
        id: "meal4",
        name: "Greek Yogurt Parfait",
        type: "snack",
        calories: 400,
        macros: { protein: 30, carbs: 70, fat: 5 },
        ingredients: ["Greek yogurt", "mixed berries", "granola", "honey"],
        prepTime: 5,
        cookTime: 0,
        imageUrl: "/images/meals/meal-greek-yogurt-parfait.jpg",
      },
    ],
    createdAt: "2024-01-10T08:00:00Z",
    updatedAt: "2024-01-10T08:00:00Z",
  },
  {
    id: "m2",
    title: "Mediterranean Balance",
    description:
      "Heart-healthy eating inspired by the Mediterranean diet. Rich in healthy fats, whole grains, and fresh produce.",
    dietType: "mediterranean",
    macros: { protein: 100, carbs: 250, fat: 90, fiber: 40 },
    allergyTags: [],
    totalCalories: 2200,
    thumbnailUrl: "/images/programs/meal-plan-mediterranean-balance.jpg",
    meals: [
      {
        id: "meal5",
        name: "Mediterranean Breakfast Bowl",
        type: "breakfast",
        calories: 450,
        macros: { protein: 20, carbs: 55, fat: 18 },
        ingredients: ["feta cheese", "tomatoes", "cucumber", "olives", "whole grain pita", "hummus"],
        prepTime: 10,
        cookTime: 0,
        imageUrl: "/images/programs/meal-plan-1504674900247.jpg",
      },
      {
        id: "meal6",
        name: "Grilled Fish Plate",
        type: "lunch",
        calories: 550,
        macros: { protein: 45, carbs: 40, fat: 25 },
        ingredients: ["grilled sea bass", "couscous", "roasted vegetables", "tzatziki"],
        prepTime: 15,
        cookTime: 20,
        imageUrl: "/images/meals/meal-grilled-fish-plate.jpg",
      },
      {
        id: "meal7",
        name: "Lamb Souvlaki Bowl",
        type: "dinner",
        calories: 700,
        macros: { protein: 40, carbs: 75, fat: 28 },
        ingredients: ["lamb souvlaki", "rice pilaf", "Greek salad", "pita bread"],
        prepTime: 20,
        cookTime: 25,
        imageUrl: "/images/meals/meal-lamb-souvlaki-bowl.jpg",
      },
      {
        id: "meal8",
        name: "Mixed Nuts & Dates",
        type: "snack",
        calories: 500,
        macros: { protein: 15, carbs: 80, fat: 19 },
        ingredients: ["almonds", "walnuts", "dates", "dried apricots"],
        prepTime: 2,
        cookTime: 0,
        imageUrl: "/images/meals/meal-mixed-nuts-dates.jpg",
      },
    ],
    createdAt: "2024-01-11T08:00:00Z",
    updatedAt: "2024-01-11T08:00:00Z",
  },
  {
    id: "m3",
    title: "Low Carb Keto",
    description:
      "Achieve ketosis with this carefully balanced low-carb meal plan. High in healthy fats and moderate protein.",
    dietType: "keto",
    macros: { protein: 130, carbs: 30, fat: 150, fiber: 20 },
    allergyTags: ["gluten-free"],
    totalCalories: 2000,
    thumbnailUrl: "/images/programs/meal-plan-low-carb-keto.jpg",
    meals: [
      {
        id: "meal9",
        name: "Keto Breakfast Plate",
        type: "breakfast",
        calories: 550,
        macros: { protein: 30, carbs: 5, fat: 45 },
        ingredients: ["bacon", "eggs", "avocado", "cheese", "spinach"],
        prepTime: 5,
        cookTime: 15,
        imageUrl: "/images/programs/meal-plan-1525351484163.jpg",
      },
      {
        id: "meal10",
        name: "Cobb Salad",
        type: "lunch",
        calories: 500,
        macros: { protein: 40, carbs: 10, fat: 35 },
        ingredients: ["grilled chicken", "bacon", "hard-boiled eggs", "avocado", "blue cheese", "greens"],
        prepTime: 20,
        cookTime: 0,
        imageUrl: "/images/meals/meal-cobb-salad.jpg",
      },
      {
        id: "meal11",
        name: "Ribeye Steak Dinner",
        type: "dinner",
        calories: 700,
        macros: { protein: 50, carbs: 8, fat: 55 },
        ingredients: ["ribeye steak", "asparagus", "butter", "garlic", "mushrooms"],
        prepTime: 10,
        cookTime: 20,
        imageUrl: "/images/meals/meal-ribeye-steak-dinner.jpg",
      },
      {
        id: "meal12",
        name: "Fat Bombs",
        type: "snack",
        calories: 250,
        macros: { protein: 10, carbs: 7, fat: 15 },
        ingredients: ["coconut oil", "cocoa powder", "almond butter", "stevia"],
        prepTime: 15,
        cookTime: 0,
        imageUrl: "/images/meals/meal-fat-bombs.jpg",
      },
    ],
    createdAt: "2024-01-12T08:00:00Z",
    updatedAt: "2024-01-12T08:00:00Z",
  },
  {
    id: "m4",
    title: "Plant-Powered Vegan",
    description:
      "Complete nutrition from plant sources. Carefully balanced to ensure you get all essential nutrients.",
    dietType: "vegan",
    macros: { protein: 90, carbs: 300, fat: 65, fiber: 55 },
    allergyTags: ["dairy-free", "egg-free"],
    totalCalories: 2100,
    thumbnailUrl: "/images/meals/meal-cobb-salad.jpg",
    meals: [
      {
        id: "meal13",
        name: "Smoothie Bowl",
        type: "breakfast",
        calories: 450,
        macros: { protein: 15, carbs: 75, fat: 12 },
        ingredients: ["frozen berries", "banana", "almond milk", "chia seeds", "granola", "coconut flakes"],
        prepTime: 10,
        cookTime: 0,
        imageUrl: "/images/programs/meal-plan-1590301157890.jpg",
      },
      {
        id: "meal14",
        name: "Buddha Bowl",
        type: "lunch",
        calories: 580,
        macros: { protein: 25, carbs: 80, fat: 18 },
        ingredients: ["quinoa", "chickpeas", "roasted sweet potato", "kale", "tahini dressing"],
        prepTime: 15,
        cookTime: 30,
        imageUrl: "/images/programs/meal-plan-high-protein-meal-plan.jpg",
      },
      {
        id: "meal15",
        name: "Thai Curry",
        type: "dinner",
        calories: 650,
        macros: { protein: 25, carbs: 85, fat: 25 },
        ingredients: ["tofu", "coconut milk", "Thai curry paste", "vegetables", "jasmine rice"],
        prepTime: 15,
        cookTime: 25,
        imageUrl: "/images/meals/meal-thai-curry.jpg",
      },
      {
        id: "meal16",
        name: "Trail Mix",
        type: "snack",
        calories: 420,
        macros: { protein: 25, carbs: 60, fat: 10 },
        ingredients: ["mixed nuts", "seeds", "dark chocolate chips", "dried fruit"],
        prepTime: 2,
        cookTime: 0,
        imageUrl: "/images/meals/meal-trail-mix.jpg",
      },
    ],
    createdAt: "2024-01-13T08:00:00Z",
    updatedAt: "2024-01-13T08:00:00Z",
  },
];

// =============================================================================
// Goals
// =============================================================================
export const defaultGoals: Goal[] = [
  {
    id: "g1",
    goalName: "Lose 10 lbs",
    description: "Achieve a healthier weight through consistent exercise and balanced nutrition.",
    targetValue: 10,
    currentValue: 3,
    unit: "lbs",
    isCompleted: false,
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-15T08:00:00Z",
  },
  {
    id: "g2",
    goalName: "Complete 20 Workouts",
    description: "Build a consistent workout habit by completing 20 workouts this month.",
    targetValue: 20,
    currentValue: 8,
    unit: "workouts",
    isCompleted: false,
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-15T08:00:00Z",
  },
  {
    id: "g3",
    goalName: "Run 5K",
    description: "Build your running endurance to complete a 5K run without stopping.",
    targetValue: 5,
    currentValue: 2.5,
    unit: "km",
    isCompleted: false,
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-15T08:00:00Z",
  },
];

// =============================================================================
// Achievements
// =============================================================================
export const achievements: Achievement[] = [
  {
    id: "a1",
    title: "First Workout",
    description: "Complete your first workout",
    iconName: "trophy",
    isUnlocked: true,
    unlockedAt: "2024-01-02T08:00:00Z",
  },
  {
    id: "a2",
    title: "7-Day Streak",
    description: "Work out for 7 consecutive days",
    iconName: "flame",
    isUnlocked: true,
    unlockedAt: "2024-01-10T08:00:00Z",
  },
  {
    id: "a3",
    title: "Early Bird",
    description: "Complete 5 morning workouts",
    iconName: "sunrise",
    isUnlocked: false,
  },
  {
    id: "a4",
    title: "Calorie Crusher",
    description: "Burn 5,000 calories total",
    iconName: "zap",
    isUnlocked: false,
  },
  {
    id: "a5",
    title: "Program Finisher",
    description: "Complete a full workout program",
    iconName: "award",
    isUnlocked: false,
  },
  {
    id: "a6",
    title: "30-Day Legend",
    description: "Maintain a 30-day workout streak",
    iconName: "crown",
    isUnlocked: false,
  },
];

// =============================================================================
// User Progress (Demo)
// =============================================================================
export const demoUserProgress: UserProgress = {
  userId: "demo-user",
  workoutsCompleted: 23,
  totalMinutes: 645,
  totalCaloriesBurned: 4850,
  currentStreak: 5,
  longestStreak: 12,
  weeklyProgress: [
    { weekStart: "2024-01-01", workoutsCompleted: 4, minutesExercised: 120, caloriesBurned: 800 },
    { weekStart: "2024-01-08", workoutsCompleted: 5, minutesExercised: 150, caloriesBurned: 1100 },
    { weekStart: "2024-01-15", workoutsCompleted: 6, minutesExercised: 180, caloriesBurned: 1350 },
    { weekStart: "2024-01-22", workoutsCompleted: 5, minutesExercised: 140, caloriesBurned: 1050 },
    { weekStart: "2024-01-29", workoutsCompleted: 3, minutesExercised: 55, caloriesBurned: 550 },
  ],
  achievements: achievements,
};

// =============================================================================
// Brand Campaigns (B2B Demo Data)
// =============================================================================
export const brandCampaigns: BrandCampaign[] = [
  {
    id: "bc1",
    brandName: "FitFuel Supplements",
    campaignName: "New Year New You",
    startDate: "2024-01-01",
    endDate: "2024-02-28",
    status: "active",
    budget: 50000,
    spent: 32500,
    impressions: 125000,
    clicks: 8500,
    conversions: 420,
    createdAt: "2023-12-15T08:00:00Z",
    updatedAt: "2024-01-20T08:00:00Z",
  },
  {
    id: "bc2",
    brandName: "PowerGear Equipment",
    campaignName: "Home Gym Essentials",
    startDate: "2024-01-15",
    endDate: "2024-03-15",
    status: "active",
    budget: 35000,
    spent: 12000,
    impressions: 75000,
    clicks: 4200,
    conversions: 180,
    createdAt: "2024-01-10T08:00:00Z",
    updatedAt: "2024-01-20T08:00:00Z",
  },
  {
    id: "bc3",
    brandName: "NutriBowl",
    campaignName: "Healthy Eating Challenge",
    startDate: "2023-11-01",
    endDate: "2023-12-31",
    status: "completed",
    budget: 25000,
    spent: 24800,
    impressions: 180000,
    clicks: 12000,
    conversions: 650,
    createdAt: "2023-10-20T08:00:00Z",
    updatedAt: "2024-01-05T08:00:00Z",
  },
];

// =============================================================================
// Sponsored Challenges
// =============================================================================
export const sponsoredChallenges: SponsoredChallenge[] = [
  {
    id: "sc1",
    brandId: "bc1",
    title: "30-Day Shred Challenge",
    description: "Complete 30 days of HIIT workouts and win exclusive prizes from FitFuel!",
    startDate: "2024-02-01",
    endDate: "2024-03-01",
    reward: "$500 FitFuel gift card",
    participants: 1250,
    completions: 0,
    thumbnailUrl: "/images/workouts/workout-1517836357463.jpg",
    workoutProgramId: "p1",
  },
  {
    id: "sc2",
    brandId: "bc2",
    title: "Home Workout Hero",
    description: "Work out at home for 14 days straight using only bodyweight exercises!",
    startDate: "2024-01-20",
    endDate: "2024-02-03",
    reward: "Resistance band set",
    participants: 890,
    completions: 234,
    thumbnailUrl: "/images/workouts/workout-core-crusher.jpg",
  },
];

// =============================================================================
// Product Placements
// =============================================================================
export const productPlacements: ProductPlacement[] = [
  {
    id: "pp1",
    brandId: "bc1",
    productName: "Premium Whey Protein",
    productType: "supplement",
    placementLocation: "post-workout",
    imageUrl: "/images/workouts/workout-1593095948071.jpg",
    linkUrl: "https://example.com/protein",
    impressions: 45000,
    clicks: 2100,
    isActive: true,
  },
  {
    id: "pp2",
    brandId: "bc2",
    productName: "Adjustable Dumbbells",
    productType: "equipment",
    placementLocation: "workout-detail",
    imageUrl: "/images/workouts/workout-morning-hiit-blast.jpg",
    linkUrl: "https://example.com/dumbbells",
    impressions: 32000,
    clicks: 1800,
    isActive: true,
  },
  {
    id: "pp3",
    brandId: "bc3",
    productName: "Healthy Meal Kit",
    productType: "food",
    placementLocation: "meal-plan",
    imageUrl: "/images/programs/meal-plan-high-protein-meal-plan.jpg",
    linkUrl: "https://example.com/mealkit",
    impressions: 28000,
    clicks: 950,
    isActive: false,
  },
];

// =============================================================================
// Recovery Activities
// =============================================================================
export const recoveries: Recovery[] = [
  {
    id: "r1",
    title: "Guided Meditation for Athletes",
    description:
      "A 15-minute meditation session designed specifically for athletes to reduce stress, improve focus, and enhance recovery. Perfect after intense training sessions.",
    type: "mental-wellness",
    duration: 15,
    difficulty: "beginner",
    thumbnailUrl: "/images/workouts/workout-1544367567.jpg",
    benefits: [
      "Reduces stress and anxiety",
      "Improves sleep quality",
      "Enhances mental clarity",
      "Boosts recovery",
    ],
    instructions: [
      "Find a quiet, comfortable space",
      "Sit or lie down in a relaxed position",
      "Close your eyes and focus on your breath",
      "Follow the guided meditation",
      "Allow thoughts to pass without judgment",
    ],
    tags: ["meditation", "mental-health", "stress-relief", "recovery"],
    createdAt: "2024-01-20T08:00:00Z",
    updatedAt: "2024-01-20T08:00:00Z",
  },
  {
    id: "r2",
    title: "Deep Tissue Sports Massage Guide",
    description:
      "Learn self-massage techniques to target muscle tension, improve circulation, and accelerate recovery. Includes techniques for common problem areas.",
    type: "sports-massage",
    duration: 20,
    difficulty: "beginner",
    thumbnailUrl: "/images/workouts/workout-1518611012118.jpg",
    benefits: [
      "Relieves muscle tension",
      "Improves blood circulation",
      "Reduces soreness",
      "Enhances flexibility",
    ],
    instructions: [
      "Start with light pressure and gradually increase",
      "Focus on areas of tension",
      "Use circular motions",
      "Hold pressure on trigger points for 30-60 seconds",
      "Finish with gentle stretching",
    ],
    tags: ["massage", "recovery", "muscle-relief", "self-care"],
    createdAt: "2024-01-21T08:00:00Z",
    updatedAt: "2024-01-21T08:00:00Z",
  },
  {
    id: "r3",
    title: "Post-Workout Stretching Routine",
    description:
      "A comprehensive 20-minute stretching routine to improve flexibility, reduce muscle stiffness, and promote recovery after workouts.",
    type: "stretching",
    duration: 20,
    difficulty: "beginner",
    thumbnailUrl: "/images/workouts/workout-1526506118085.jpg",
    benefits: [
      "Improves flexibility",
      "Reduces muscle stiffness",
      "Prevents injury",
      "Promotes relaxation",
    ],
    instructions: [
      "Warm up with light movement",
      "Hold each stretch for 30-60 seconds",
      "Breathe deeply during stretches",
      "Don't bounce or force movements",
      "Focus on major muscle groups",
    ],
    tags: ["stretching", "flexibility", "recovery", "post-workout"],
    createdAt: "2024-01-22T08:00:00Z",
    updatedAt: "2024-01-22T08:00:00Z",
  },
  {
    id: "r4",
    title: "Breathing Exercises for Recovery",
    description:
      "Simple breathing techniques to activate your parasympathetic nervous system, reduce stress, and enhance recovery between training sessions.",
    type: "breathing",
    duration: 10,
    difficulty: "beginner",
    thumbnailUrl: "/images/workouts/workout-1571019614242.jpg",
    benefits: [
      "Reduces stress hormones",
      "Improves oxygen delivery",
      "Enhances relaxation",
      "Supports recovery",
    ],
    instructions: [
      "Find a comfortable seated position",
      "Inhale deeply through your nose for 4 counts",
      "Hold your breath for 4 counts",
      "Exhale slowly through your mouth for 6 counts",
      "Repeat for 5-10 cycles",
    ],
    tags: ["breathing", "stress-relief", "recovery", "mental-wellness"],
    createdAt: "2024-01-23T08:00:00Z",
    updatedAt: "2024-01-23T08:00:00Z",
  },
  {
    id: "r5",
    title: "Foam Rolling Full Body",
    description:
      "A complete foam rolling routine to release muscle tension, improve mobility, and speed up recovery. Targets all major muscle groups.",
    type: "foam-rolling",
    duration: 25,
    difficulty: "intermediate",
    thumbnailUrl: "/images/workouts/workout-upper-body.jpg",
    benefits: [
      "Releases muscle knots",
      "Improves mobility",
      "Reduces delayed onset muscle soreness",
      "Enhances blood flow",
    ],
    instructions: [
      "Start with light pressure",
      "Roll slowly over each muscle group",
      "Pause on tender spots for 30-60 seconds",
      "Breathe deeply during rolling",
      "Work from bottom to top",
    ],
    tags: ["foam-rolling", "mobility", "recovery", "self-massage"],
    createdAt: "2024-01-24T08:00:00Z",
    updatedAt: "2024-01-24T08:00:00Z",
  },
  {
    id: "r6",
    title: "Evening Wind-Down Meditation",
    description:
      "A gentle 20-minute meditation to help you unwind after a long day, improve sleep quality, and prepare your body for recovery.",
    type: "mental-wellness",
    duration: 20,
    difficulty: "beginner",
    thumbnailUrl: "/images/workouts/image-1604329760661.jpg",
    benefits: [
      "Improves sleep quality",
      "Reduces evening stress",
      "Promotes relaxation",
      "Supports recovery",
    ],
    instructions: [
      "Dim the lights",
      "Lie down comfortably",
      "Focus on your breath",
      "Release tension from each body part",
      "Allow yourself to drift into relaxation",
    ],
    tags: ["meditation", "sleep", "relaxation", "mental-wellness"],
    createdAt: "2024-01-25T08:00:00Z",
    updatedAt: "2024-01-25T08:00:00Z",
  },
  {
    id: "r7",
    title: "Cryotherapy Session",
    description:
      "Experience the benefits of whole-body cryotherapy. Rapid cold exposure reduces inflammation, speeds recovery, and boosts energy. Professional supervised sessions in our state-of-the-art cryotherapy chamber.",
    type: "cryotherapy",
    duration: 3,
    difficulty: "beginner",
    thumbnailUrl: "/images/workouts/image-1606312619070.jpg",
    benefits: [
      "Reduces inflammation and muscle soreness",
      "Speeds up recovery time",
      "Boosts energy and mood",
      "Improves sleep quality",
      "Enhances athletic performance",
    ],
    instructions: [
      "Arrive 10 minutes before your appointment",
      "Wear minimal clothing (provided protective gear)",
      "Session lasts 2-3 minutes at -200°F",
      "Professional supervision throughout",
      "Post-session light movement recommended",
    ],
    tags: ["cryotherapy", "recovery", "inflammation", "performance"],
    requiresBooking: true,
    price: 45,
    createdAt: "2024-01-26T08:00:00Z",
    updatedAt: "2024-01-26T08:00:00Z",
  },
  {
    id: "r8",
    title: "Infrared Sauna Therapy",
    description:
      "Relax and recover in our premium infrared sauna. Deep tissue heating promotes muscle recovery, detoxification, and stress relief. Perfect for post-workout recovery or general wellness.",
    type: "sauna",
    duration: 30,
    difficulty: "beginner",
    thumbnailUrl: "/images/workouts/image-1606923829579.jpg",
    benefits: [
      "Deep muscle relaxation",
      "Detoxification through sweating",
      "Reduces muscle tension",
      "Improves circulation",
      "Stress relief and mental clarity",
    ],
    instructions: [
      "Arrive hydrated and bring water",
      "Session typically lasts 20-30 minutes",
      "Temperature ranges from 120-140°F",
      "Relax and breathe deeply",
      "Cool down gradually after session",
    ],
    tags: ["sauna", "detox", "relaxation", "recovery", "wellness"],
    requiresBooking: true,
    price: 35,
    createdAt: "2024-01-27T08:00:00Z",
    updatedAt: "2024-01-27T08:00:00Z",
  },
];

// =============================================================================
// Coupons
// =============================================================================
export const coupons: Coupon[] = [
  {
    id: "c1",
    brandId: "bc1",
    code: "FITSTART20",
    description: "20% off your first order",
    discountType: "percentage",
    discountValue: 20,
    minPurchase: 50,
    maxUses: 1000,
    usedCount: 342,
    expiresAt: "2024-03-31",
    isActive: true,
  },
  {
    id: "c2",
    brandId: "bc2",
    code: "HOMEGYM50",
    description: "$50 off equipment orders over $200",
    discountType: "fixed",
    discountValue: 50,
    minPurchase: 200,
    maxUses: 500,
    usedCount: 128,
    expiresAt: "2024-02-28",
    isActive: true,
  },
  {
    id: "c3",
    brandId: "bc3",
    code: "HEALTHYEATS",
    description: "Free shipping on meal kits",
    discountType: "fixed",
    discountValue: 15,
    maxUses: 2000,
    usedCount: 1850,
    expiresAt: "2024-01-31",
    isActive: false,
  },
];

